{
 "title": "Мониторинг сервиса предсказания цены",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Время работы эндпоинта",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, price_prediction_duration_seconds_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, price_prediction_duration_seconds_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, price_prediction_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов для каждого эндпоинта",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доля запросов по эндпоинтам и статусам",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Медианное значение предсказания",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "price_prediction_median", "legendFormat": "__auto" }
   ]
  }
 ]
}