channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - catboost==1.2.8
  - ipython==8.37.0
  - numpy==1.26.4
  - pandas==2.3.1
  - scipy==1.15.3
name: mlflow-env
